### PR TITLE
Added instructions

### PR DESCRIPTION
**Pull request by dcoric**
1. Updated home page to display instructions for the users to simplify YuniKorn integration
2. Added prettier configuration

### CODE REVIEW

**Review by fabiovincenzi — COMMENTED** [review]
@dcoric, I took a look at this, I think the instructions are clear! The only thing I am noticing is that I can't see the images you added in the document, maybe they were not tracked because of the `.gitignore`.

**Comment by dcoric** [comment]
> @dcoric, I took a look at this, I think the instructions are clear! The only thing I am noticing is that I can't see the images you added in the document, maybe they were not tracked because of the `.gitignore`.

Looks like .gitignore from the root project prevented committing changes in angular assets. I have fixed it

**Comment by dejanzele** [comment]
Since it is a PR for instructions, can you add instructions in the README.md how to run it? :)

**Comment by dcoric** [comment]
> Since it is a PR for instructions, can you add instructions in the README.md how to run it? :)



> Since it is a PR for instructions, can you add instructions in the README.md how to run it? :)

I have appended README.md with an update for users on what to expect to see on this home page. This documentation covers the 'next' step after the YHS is running and that is the connection with the YuniKorn Web. It generates parameters that can be copy-pasted to the YuniKorn Web config file.

**Review by fabiovincenzi — APPROVED** [review]
LGTM

**Pull request merged**
